### ISSUE TITLE
Survey: which .Net framework should Http-Multipart-Data-Parser support?

### ISSUE THREAD

**Issue by Jericho** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#101]
Last time we reviewed the supported frameworks was almost 2 years ago (see [here](#73)) so I figured it was time to go through this exercise again. 

Http-Multipart-Data-Parser currently targets net461, net472, netstandard2.0 but I'm wondering if we could completely drop support for "full" framework (i.e. net461 and net472)? Is that too disruptive though? Is anybody still using the "full" framework? Maybe replacing these two targets with net48 would be a less disruptive approach?

As far as .NET "core", Microsoft has dropped support for 2.0 in October 2018 and 2.1 is the current version under "long term support (see here). Support for 2.0 ended about 2 and a half years ago so I am pretty confident that developers had enough time to upgrade by now.

I'm trying to strike a balance between supporting the greatest number of developers (no matter which version of the .NET they target) and getting rid of older, unsupported versions of .NET.

What I'm thinking about doing is:

remove net461, net472 and replace them with net48
remove netstandard2.0 and replace it with netstandard2.1

This would be in addition to targeting net5.0 which is tracked in [this ticket](#100)

Here's an [interesting article](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/) on this topic.

Let me know what you think. I'm looking forward for your feedback.

**Comment by jstedfast** [comment]
Ask yourself this question:

What functionality would dropping netstandard2.0 and adding netstandard2.1 gain you? If nothing, then continue targeting netstandard2.0.
