### ISSUE TITLE
Question: producing multipart message

### ISSUE THREAD

**Issue by Kemyke** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#103]
Thanks for the great library, I have to consume a webservice with multipart messages and this library help me a lot.
I was just wondering, have you ever thought to extend this library with producing the multipart xml message. I mean to fill the Parameters and Files lists and serialize it to a stream or string? 
What do you think, is it a feature which fits in this library?

**Comment by Jericho** [comment]
@Kemyke I haven't heard from you in a while so I am closing this issue but feel free to post a comment if you want to resume the discussion and I will be happy to reopen.
