### ISSUE TITLE
Drop support for outdated frameworks (net461, net472 and netstandard2.0)

### ISSUE THREAD

**Issue by Jericho** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#105]
I started [thinking](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/issues/101) about dropping support for frameworks that have reached end-of-life (or will reach it soon or have been replaced by a framework version that will be supported longer-term) a while ago and I intend to implement the following changes in the next major release:

- Drop net461 and net472 and replace them with net48
- Drop netstandard2.0 and replace it with netstandard2.1
- Add support for net6.0

**Comment by groege** [comment]
> * et461 and net472 and replace them with net48
> * Drop netstandard2.0 and replace it with netstandard2.1
> * Add support for net6.0

Please do not! Many projects including ours rely on 4.8 and cannot be migrated...
I'm also pretty sure we are not the only ones - there is so much legacy code that has still to be maintained and kept up to date to ensure IT security (we also have contracts to update libraries when possible)

**Comment by Jericho** [comment]
> Many projects including ours rely on 4.8 and cannot be migrated...

I indicated that I would replace the net461 and net472 with net48 so I don't understand your objection.
