### ISSUE TITLE
FilePart additional properties key name gets changed

### ISSUE THREAD

**Issue by joeyeng** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#112]
The key names of the FilePart additonal properties all get changed to lower case.

**Comment by Jericho** [comment]
Yes indeed. Is that problematic for you or are you simply pointing this out?

In case you are interested: the parser tracks all properties in a private dictionary and the names of these properties have always been lower-case'd. I was able to go as far back as January 2013 in the repo history to double check and I can confirm that's how they have always been tracked. I wasn't maintaining this project back then so I can't say for sure why that is, but I suspect it has to do with the fact that C# dictionaries are case-sensitive by default.

I'll do some research to see what it would take to preserve the casing but I'm curious to hear from you what kind of problem you are experiencing with the current situation.

**Comment by joeyeng** [comment]
Thanks for the quick response! Fortunately, changing the case of the keys did not break us, but we're paranoid that it will break for future users of our service.

**Comment by joeyeng** [comment]
Works great. Thanks for the fix!
