### ISSUE TITLE
not able to parse base64 string and json from response

### ISSUE THREAD

**Issue by dcmstc** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#119]
```
--jQBPLssoJVYilQMXuUc-Sue8
Content-Type: application/json
Content-Disposition: form-data; name="personname"

{"personname":{"firstname":"andry"}

--jQBPLssoJVYilQMXuUc-Sue8
Content-Type: application/pdf
Content-Disposition: form-data; filename="pdfimage.pdf"; name="pdfimage"

JVBERi0xLjQKJaqrrK0KMSAwIG9iago8PAovUHJvZHVjZXIgKEFwYWNoZSBGT
--jQBPLssoJVYilQMXuUc-Sue8
```

above is the response parser parses the data with the method
```csharp
var parser = await MultipartFormDataParser.ParseAsync(stream); 
parser.Files.SingleOrDefault(f => f.Name == "labelImage")?.Data
```
however, I get data from the Data object (stream) but it is not the same as base64 even when I store the string to file it shows me a pdf corrupted message

**Comment by Jericho** [comment]
First of all, the sample payload you posted is missing a closing boundary. I'm guessing you simply posted a subset of the actual data for the sake of simplicity.

Second, the data in the `pdfimage` section seems very small to me. So, again, I will assume you simply posted a subset of the actual data for the sake of simplicity.

Third, I wrote a unit test which I think mimics your scenario and I see no problem at all. The unit test completes successfully.

Can you provide more details, repro steps, actual error messages, etc. 
Bottom line: I will need you to provide more information, repro steps, actual error messages, etc.  in order to investigate some more.

Here's the unit test I used:
```csharp
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace HttpMultipartParser.UnitTests.ParserScenarios
{
	public class PDF
	{
		private static readonly string _testData = TestUtil.TrimAllLines(
			@"--jQBPLssoJVYilQMXuUc-Sue8
			Content-Type: application/json
			Content-Disposition: form-data; name=""personname""

			{""personname"":{""firstname"":""andry""}

			--jQBPLssoJVYilQMXuUc-Sue8
			Content-Type: application/pdf
			Content-Disposition: form-data; filename=""pdfimage.pdf""; name=""pdfimage""

			JVBERi0xLjQKJaqrrK0KMSAwIG9iago8PAovUHJvZHVjZXIgKEFwYWNoZSBGT
			--jQBPLssoJVYilQMXuUc-Sue8--"
		);

		/// <summary>
		///     Test case for single files.
		/// </summary>
		private static readonly TestData _testCase = new TestData(
			_testData,
			new List<ParameterPart> {
				new ParameterPart("personname", "{\"personname\":{\"firstname\":\"andry\"}\r\n")
			},
			new List<FilePart> {
				new FilePart("pdfimage", "pdfimage.pdf", TestUtil.StringToStreamNoBom("JVBERi0xLjQKJaqrrK0KMSAwIG9iago8PAovUHJvZHVjZXIgKEFwYWNoZSBGT"), "application/pdf", "form-data")
			}
	   );

		/// <summary>
		///     Initializes the test data before each run, this primarily
		///     consists of resetting data stream positions.
		/// </summary>
		public PDF()
		{
			foreach (var filePart in _testCase.ExpectedFileData)
			{
				filePart.Data.Position = 0;
			}
		}

		[Fact]
		public void PDFTest()
		{
			using (Stream stream = TestUtil.StringToStream(_testCase.Request, Encoding.UTF8))
			{
				var parser = MultipartFormDataParser.Parse(stream);
				Assert.True(_testCase.Validate(parser));
			}
		}

		[Fact]
		public async Task PDFTest_Async()
		{
			using (Stream stream = TestUtil.StringToStream(_testCase.Request, Encoding.UTF8))
			{
				var parser = await MultipartFormDataParser.ParseAsync(stream, Encoding.UTF8);
				Assert.True(_testCase.Validate(parser));
			}
		}
	}
}
```

**Comment by dcmstc** [comment]
Thank you for your response,

as you told I am attaching the response file to this which contains the full response.

Got your code but I am not able to find how to break down the response into parameters and files, I know from the response we are getting 1 JSON and 1 base64 string.

**Please tell me how to parse or get parameter and file as base64 string.** Please give me a method to get those values for the response or share code for the parse response.

[Test Multipart.txt](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/files/14585757/Test.Multipart.txt)

**Comment by Jericho** [comment]
I encourage you to read the project's ReadMe file, it shows several C# code samples that are relevant to the question you are asking. For instance, you'll see several examples where we get the content of a parameter by invoking the `GetParameterValue` method like in this example:

```csharp
var username = parser.GetParameterValue("username");
var email = parser.GetParameterValue("email");
```

You could also using Linq to query the parameters for the one you are looking for like this example:
```csharp
var myParameterValue = parser.Parameters
	.Where(p => p.Name == "The_name_of_your_desired_parameter")
	.Select(p => p.Data);
``

Alternatively, you could loop through the list of parameters like this:
```csharp
foreach (var parameter in parser.Parameters)
{
	Debug.WriteLine($"Parameter name: {parameter.Name}. Value: {parameter.Data}");
}
```

Similarly, you can use Linq to query the files for the one that matches your expectations like this:
```csharp
var file = parser.Files.First(p => p.Name == "The_name_of_your_desired_file")
Debug.WriteLine($"Saving {file.Name} to disk...");
using (FileStream fileStream = new FileStream($"C:\\temp\\{file.FileName}", FileMode.Create))
{
	file.Data.CopyTo(fileStream);
}
```

Hopefully this helps

**Comment by dcmstc** [comment]
Hi,

This approach I did, but the issue was when we saved this file, it was a corrupted file when we open.

Even when you take that object (Data /stream ) and do the return process to convert to base64 from stream then you can see that it is different from what we have in the original input file.

attached pdf for reference. 

[labelImage.pdf](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/files/14598076/labelImage.pdf)

**Comment by Jericho** [comment]
Have you tried decoding the base64 encoded content before saving to a PDF file? Something along these lines:

```csharp
var file = parser.Files.First(p => p.Name == "labelImage"); // 'labelImage' is the name of the file in the sample you previously provided
Debug.WriteLine($"Saving {file.Name} to disk...");
using (FileStream fileStream = new FileStream($"C:\\temp\\{file.FileName}", FileMode.Create))
{
	using (var reader = new StreamReader(file.Data))
	{
		// Read and decode the base64 encoded content
		var decodedContent = Convert.FromBase64String(reader.ReadToEnd());

		// Write the decoded content to disk
		var writer = new BinaryWriter(fileStream);
		writer.Write(decodedContent, 0, decodedContent.Length);
		writer.Close();
	}
}
```

**Comment by dcmstc** [comment]
Thank you Very much.
Now it's working, pdfs are opening.
