### ISSUE TITLE
FormData object support

### ISSUE THREAD

**Issue by rosenbjerg** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#52]
I am unable to parse a FormData objects containing form information.
The received data is in the following format:
```
------WebKitFormBoundary05dwgxFHZcnKtx42
Content-Disposition: form-data; name="name"

John
------WebKitFormBoundary05dwgxFHZcnKtx42
```

**Comment by Vodurden** [comment]
Hi rosenbjerg. That looks like a malformed multipart. The final boundary in a multipart must end with `--`. For your example I believe it should look like so:

```
------WebKitFormBoundary05dwgxFHZcnKtx42
Content-Disposition: form-data; name="name"

John
------WebKitFormBoundary05dwgxFHZcnKtx42--
```

**Comment by rosenbjerg** [comment]
Sorry, my fault, this was just a bit of the full data. The last boundary does end with 
------WebKitFormBoundary05dwgxFHZcnKtx42--
The problem was that i was sending a file using the FormData object, but i get 'Unexpected end of stream'-exception when trying to parse and save it the drive.
Other than that problem, the StreamingMultipartFormDataParser has been of good use to me :)

**Comment by Vodurden** [comment]
Ahh I see. So the error was caused by having file data in something marked as form data. 

Yeah if we try and read a file like it's form-data we'll definitely run into issue.

**Comment by rosenbjerg** [comment]
Yes. I followed [this guide](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects) to upload a file using the FormData object. But when using the StreamingMultipartFormDataParser to parse the request body, it throws the 'Unexpected end of stream'-exception

**Comment by Jericho** [comment]
@rosenbjerg I know it's been three years since you raised this issue but I recently took over stewardship of this project and I'm trying to address outstanding issues. If this is still a problem, I'd like to take a look at it and try to find a solution. Let me know if this is still a problem (FYI: I published a few releases in the last months so make sure to upgrade to the latest.)

Thanks

**Comment by rosenbjerg** [comment]
It's no longer a problem for as I've moved to aspnet core and the inbuilt form parser.
So you can just close this issue :)

**Comment by Jericho** [comment]
Ok. Thanks for letting me know. I appreciate it.
