### ISSUE TITLE
call the parse twice

### ISSUE THREAD

**Issue by dnamna** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#66]
So am trying to call the parser twice,I have two WCF services on two different servers.
I am able to parse the Stream on first web service however when I send the stream to the second server and try to parse it,it throws an exception "**Value cannot be null. Parameter name: source**" on 

`reader.ReadLine().Skip(2)`

**Comment by Jericho** [comment]
@dnamna In my experience you get this error message when the pointer in the stream passed to the `MultipartFormDataParser` is not positioned at the beginning. Personally, I always make sure to re position the pointer to the beginning of the stream like so:

```
// It's important to rewind the stream
stream.Position = 0;

// Parse the multipart content
var parser = new MultipartFormDataParser(stream, Encoding.UTF8);
```

Hopefully this helps.

**Comment by Jericho** [comment]
Closing this issue. Feel free to reopen if my suggestion did not help.
