### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by Jericho** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#72]
To ensure we are consistent, I will automate the release process.

- [x] Use gitflow
- [x] Use a [Cake](https://cakebuild.net/) script to increase version number, build, run unit tests and pack
- [ ] Use Appveyor to automatically build the project when a commit is detected on some pre-determined branches (such as master, release/*, etc.)
- [x] Create a 'milestone' for each release and assign issues to the appropriate milestone. 
- [x] Create a 'release' in GitHub and document bug fixes, enhancements, etc included in a given release (This is typically a manual step but I have a Cake script that can automate the creation of the release and also summarize resolved issues associated with the milestone). Users can refer to this 'release' after a package is published to Nuget for release notes.
- [x] By default, the 'release' is in draft mode. As soon as the release is published, a build is triggered on Appveyor and package published to nuget
- [x] Organize files to make it easier to automate process. For instance, move source code in a new folder called ’source’, etc.
- [x] Add various configuration file in root folder such as appveyor.yml, .editorconfig, etc.

**Comment by Jericho** [comment]
@Vodurden I am in the process of setting up gitflow but I do not have access to the repo's settings so can you please change the following:

1. `develop` should be the default branch against which all pull requests are made. Under 'Settings' click on 'Branches', select 'develop' from the drop down and click 'update'
2. `master` should be protected. On the same setting screen where you configured the default branch make sure there is one protection rule for 'master'. I personally enable 'Require status check to pass before merging' and 'Require branches to be up to date before merging.

**Comment by Vodurden** [comment]
@Jericho: Done :+1:

**Comment by Jericho** [comment]
Thank you!

**Comment by Jericho** [comment]
Merging the branch but I won't be able to setup and test the AppVeyor integration until #76 is completed.
