### ISSUE TITLE
Formalize choice of license

### ISSUE THREAD

**Issue by Jericho** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#74]
@Vodurden Correct me if I'm wrong but I believe your intent was to use the MIT license with this project. At the time you setup this repository there was no easy way to indicate the license you selected so you [created a file](https://github.com/Vodurden/Http-Multipart-Data-Parser/commit/0c763d636c70795a28548248f08f11d2ebcdf0f6) where you copied the text of the MIT license.

Since then, the nuspec spec has been enhanced to allow package owners to [specify which license they selected](https://docs.microsoft.com/en-us/nuget/reference/nuspec#license) without having to copy/paste the actual license text.

I propose removing the text file containing the license and replacing it with the proper attrobute in the nuspec file.

**Comment by Jericho** [comment]
In addition to the file containing the text of the license, I also discovered that the nuspec contains a `licenseUrl` line (which has been deprecated). 

I will remove the text file and remove the `licenseUrl` from nuspec and replace with the proper `license` tag in the nuspec to indicate this project is licensed under MIT.

**Comment by Vodurden** [comment]
Yep, the project is licensed under MIT. I'm happy if you want to change the way that's expressed to be more aligned with GitHub and NuGet's licensing features. :+1:
