### ISSUE TITLE
Move project to an organization

### ISSUE THREAD

**Issue by Jericho** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#76]
@Vodurden Are you open to moving this project under an organization? You and I would have full admin rights so you would not lose any privilege that you currently have, but it would give me a little bit more latitude. For instance, I currently cannot setup an AppVeyor instance linked to the project because I am not the owner.

**Comment by Vodurden** [comment]
Yes I think that would be fine, given I'm not the sole contributor it doesn't make sense for it to sit under my GitHub user.

Do you need me to do the move? Or is it something you can do yourself?

**Comment by Jericho** [comment]
I created an organization and invited you to be an owner. As soon as you accept the invite, you'll be able to transfer ownership from your personal account to this new organization.

Here's GitHub's [documentation](https://help.github.com/en/github/administering-a-repository/transferring-a-repository) on the process.

**Comment by Jericho** [comment]
By the way, I couldn't think of an original name for this organization so I simply called it `Http-Multipart-Data-Parser`. Let me know if you can think of a better name.

**Comment by Vodurden** [comment]
I've transferred the repository :+1:

**Comment by Jericho** [comment]
Awesome! I was able to [setup AppVeyor](https://ci.appveyor.com/project/Jericho/http-multipart-data-parser/history) which mean that from now on releases will be automated.
