### ISSUE TITLE
"Value cannot be null. (Parameter 'source')"

### ISSUE THREAD

**Issue by inpicksys** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#78]
Happens in net.core 3
"Value cannot be null. (Parameter 'source')"

```
request.Body.Seek(0, SeekOrigin.Begin);
var reader = new StreamReader(request.Body, Encoding.UTF8, true, 1024, true);
var body = await reader.ReadToEndAsync();

request.Body.Position = 0;

var bodyContent = body;
var stream = new MemoryStream(Encoding.UTF8.GetBytes(bodyContent));

var parser = await MultipartFormDataParser.ParseAsync(stream, Encoding.UTF8).ConfigureAwait(false);
```

I have no idea how to handle this. All different variants were tried

**Comment by Jericho** [comment]
Is there a reason why you pass the request body to a stream reader, read the content as a string, convert the string to an array of bytes, pass this array to a memory stream and finally pass the memory stream to MultipartFormDataParser? Seems convoluted to me. I think you should be able to simply pass the body of the request to MultipartFormDataParser. Something along the lines of: 
```csharp
var parser = await MultipartFormDataParser.ParseAsync(request.Body, Encoding.UTF8).ConfigureAwait(false);
```

**Comment by Jericho** [comment]
I'm not saying this will necessarily solve the issue you are facing but at least it will simplify the situation.

**Comment by inpicksys** [comment]
@Jericho Thank you for reply. Yep, this is unnecessary complex manipulations with stream,
Problem solved with updating attribute  from
`	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
	public class DisableFormValueModelBindingAttribute : Attribute, IResourceFilter
	{
		public void OnResourceExecuting(ResourceExecutingContext context)
		{
			var formValueProviderFactory = context.ValueProviderFactories
				.OfType<FormValueProviderFactory>()
				.FirstOrDefault();
			if (formValueProviderFactory != null)
			{
				context.ValueProviderFactories.Remove(formValueProviderFactory);
			}

			var jqueryFormValueProviderFactory = context.ValueProviderFactories
				.OfType<JQueryFormValueProviderFactory>()
				.FirstOrDefault();
			if (jqueryFormValueProviderFactory != null)
			{
				context.ValueProviderFactories.Remove(jqueryFormValueProviderFactory);
			}
			
		}

		public void OnResourceExecuted(ResourceExecutedContext context)
		{
		}
	}`

to:

`
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
	public class DisableFormValueModelBindingAttribute : Attribute, IResourceFilter
	{
		public void OnResourceExecuting(ResourceExecutingContext context)
		{
   		       var factories = context.ValueProviderFactories;
			factories.RemoveType<FormValueProviderFactory>();
			factories.RemoveType<FormFileValueProviderFactory>();
			factories.RemoveType<JQueryFormValueProviderFactory>();
		}

		public void OnResourceExecuted(ResourceExecutedContext context)
		{
		}
	}
`
Also updated new .net core 3 middleware `AddNewtonsoftJson` ->using:
at Startup.cs:
`
services.AddControllers(options =>
			{
				options.Filters.Add(typeof(HttpGlobalExceptionFilter));
			}).AddNewtonsoftJson(options => {
				options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
				options.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.Objects;
			});
`
Maybe will be helpful for somebody. Other code remaining same (as in doc of MultiPartDataParser) -> just passing request.body -> extract file(s).
Thanks.

**Comment by Jericho** [comment]
Glad you figured it out.
