### ISSUE TITLE
"Key not found" exception when name and filename parameters are omitted

### ISSUE THREAD

**Issue by nakamura2000** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#83]
I want to use this library for parse mjpeg stream but when multipart part section doesn't have content-disposition header , key not found exception thrown.

I sent pr to fix this issue #82 .

**Comment by Jericho** [comment]
I am not familiar with mjpeg streams so can you post an example of the data you receive. Hopefully this will allow me to reproduce and understand the issue you are reporting.

**Comment by nakamura2000** [comment]
Thank you for your quick reply.

Example response code is copied from stackoverflow.
https://stackoverflow.com/questions/47729941/mjpeg-over-http-specification

Example of the data
```
Content-Type: multipart/x-mixed-replace; boundary="MOBOTIX_Fast_Serverpush"

--MOBOTIX_Fast_Serverpush
Content-Type: image/jpeg

<jpeg bytes>
--MOBOTIX_Fast_Serverpush
Content-Type: image/jpeg

<jpeg bytes>
--MOBOTIX_Fast_Serverpush
... and so on ...
--MOBOTIX_Fast_Serverpush--
```
※body part is binary jpeg data.
structure of multipart/x-mixed-replace is same as multipart/mixed
