### ISSUE TITLE
Tcp NetworkStream gets stuck until Connection closed

### ISSUE THREAD

**Issue by BeatriceThalo** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#92]
Hi, I have a question.
Is there a way to use a TcpClient NetworkStream with the MultipartFormDataParser.Parse(stream) to read a few files sent in one PUT, ranging from 1KB to 30MB.
I've read a few forums saying that a NetworkStream is a special case where the EOF isn't sent until the Tcp connection is closed, which matches my experience of the files saving locally only once the hanging postman request is cancelled.
It appears that the NetworkStream is copied over into separate MemoryStreams per file?
Also I'm testing the package functionality incrementally, so if the StreamingMultipartFormDataParser doesn't have this issue, let me know.
Thank you in advance for your insight!

**Comment by Jericho** [comment]
A NetworkStream is a stream so in theory it should work but I have to be honest, I have never tried it and I am not familiar with the caveat regarding EOF so I can't give you a definitive answer. 

Having said that, I see that you mentioned that you are handling potentially large attachments. In this scenario, the streaming parser is definitely a better alternative that allow you to handle each "chunk" as they stream as do whatever you please with this chunk of data, for example append to a file on the file system, etc. When you use MultipartFormDataParser, the entire content of all the attachments is loaded in memory which is probably not desirable in your scenario.

I hope this is helpful.

**Comment by BeatriceThalo** [comment]
Thank you for your response!
I made one edit to prevent blocking, in RebufferableBinaryReader.cs line 505

```c#
int amountRead = 0;
if (!(typeof(System.Net.Sockets.NetworkStream) == stream.GetType() && !(stream as System.Net.Sockets.NetworkStream).DataAvailable))
{
    amountRead = stream.Read(buffer, 0, bufferSize);
}
```

I tried the streaming parser, it takes about 2 minutes for all of the filehandler delegates using FileStream.Write to complete for a 24MB file, using local postman. Next challenge will be to see if that speed can improve.

**Comment by BeatriceThalo** [comment]
My speed went down to the expected 1-2 seconds after removing my extra debug print statements.

Using DataAvailable worked for me using a wired connection, but then broke for a wireless connection. 
Then I tried a quick way to utilize counting bytes read, using the `request.header.Get("Content-Length")` as the maxNetStreamLen and 
`!isNetStream || (stream as System.Net.Sockets.NetworkStream).DataAvailable || stream.Position < maxNetStreamLen)`
but stream.Position is unsupported for NetworkStream, and it looks difficult to tally how many bytes the parser has read.

So in lieu of using something other than TcpClient and NetworkStream, I wrote the whole request.networkstream to a txt file, then ran the parser on that filestream, which takes a little longer because of the duplicate effort, but also works on wireless with a speed of 4 seconds.

**Comment by Jericho** [comment]
You're not the only one who experience that [DataAvailable seems to be unreliable](https://stackoverflow.com/questions/36731247/c-sharp-networkstream-dataavailable-seems-to-be-unreliable) but the crux of the issue seems to be that data arrives over the network at a rate slower than it's read from the stream.

Glad you were able to figure out a workaround and thanks for keeping me in the loop.

**Comment by Jericho** [comment]
Check out [this StackOverflow question](https://stackoverflow.com/questions/13097269/what-is-the-correct-way-to-read-from-networkstream-in-net) and more specifically [this answer](https://stackoverflow.com/a/13097757/153084). Some people seem to have found success by increasing their network stream read timeout.

Let me know if it works for you.

**Comment by BeatriceThalo** [comment]
Thank you for the timeout tip!! I've got it working now!
I learned that over wifi:

- the networkStream.read method returns different sized chunks each time, and sometimes has a gap of time where it has an empty chunk and it throws an "I'm trying to connect" socket error. By keeping track of the running total count of bytes read, I can handle those 10035 errors with a re-read until the sum of read chunk lengths reaches the byte count specified by the request header's Content-Length. My hardware could have e.g. 1, 3, or 22 re-reads per gap, several gaps per request, each under 500ms.
- either the TcpClient (which wraps a socket) or using a Socket directly, chooses it's own bufferSize based on the size of the incoming request, so I use the request's bufferSize instead of arbitrarily choosing my own for the networkStream reading and fileStream writing.
- one mistake I had for file writing was using the bufferSize as the crop span of data to copy out of the buffer, so the different chunk size each time made a lot of residual overflow "corruptions" throughout my whole file. Using the readByteCount of the chunk to crop the buffer output for the incremental file writing solved that. 

```c#
var stream = tcpClient.GetStream();
var line = ReadLine(stream); // uses stream.ReadByte()
// ...parses the request header...
req.stream = stream;
				
if (req.headers.Get("Content-Type").Contains("multipart/form-data"))
{
    tcpClient.Client.ReceiveTimeout = 20;

    string filePathOfRequestCopy = this.tempFolderPath + "/request-raw.txt";
    var filestream = File.Create(filePathOfRequestCopy);

    // Interestingly the buffer size will automatically scale/increase roughly based on the incoming request's order of magnitude,
    // though not match it. Tested value ranged from 400kB to 1MB for 200B to 38MB requests.
    int smallMemoryBufferLength = tcpClient.ReceiveBufferSize;
    byte[] smallMemoryBuffer = new byte[smallMemoryBufferLength];
    int sumBytesRead = 0;
    int totalContentLen = Int32.Parse(req.headers.Get("Content-Length"));
    var netStreamBytesReadOneChunk = 0;
    do
    {
        try
        {
            //these read at variable length chunks over wifi,
            // sometimes with a rest time between them when the stream is empty but the maxContentLength still hasn't been fully delivered
            netStreamBytesReadOneChunk = req.stream.Read(smallMemoryBuffer, 0, smallMemoryBufferLength);
            sumBytesRead += netStreamBytesReadOneChunk;
            filestream.Write(smallMemoryBuffer, 0, netStreamBytesReadOneChunk);
        }
        catch (IOException ex)
        {
            // if the ReceiveTimeout is reached an IOException will be raised...
            // with an InnerException of type SocketException and ErrorCode 10060
            // It is an inner exception because this tcpClient wraps a Socket
            var socketExept = ex.InnerException as SocketException;

            if (socketExept == null)
            {
                // if it's not the "expected" exception, let's not hide the error
                throw ex;
            } else if (socketExept.ErrorCode == 10060 || socketExept.ErrorCode == 60)
            {
                // 10060 is the receive timeout.
                // if it is the receive timeout, then reading ended
                netStreamBytesReadOneChunk = 0;
            }
            else if (socketExept.ErrorCode == 10035)
            {
                // 10035 means its trying really hard to connect
                // and you should just give it a moment.
                netStreamBytesReadOneChunk = sumBytesRead < totalContentLen ? 1 : 0;
                // Tested value tends to be from 1, 3, or 22 retries, within an emptyTime up to 500ms
            }
            else if (socketExept.ErrorCode == 10056)
            {
                // 10056 means already connected
                netStreamBytesReadOneChunk = 0;
            } else
            {
                throw ex;
            }
        }
    } while (netStreamBytesReadOneChunk > 0);

    filestream.Position = 0;
    try
    {
        //Assumes that the current position of the stream is at the beginning of the first multipart's starting boundary.
        //A request's Content Length is given in the HTTP request header before the multiparts, so it isn't known to the parser
        req.formData = MultiPartEntry.ParseBig(filestream, tempFolderPath);
    }
    catch (Exception e)
    {
        Debug.LogError(e.ToString());
    }
    filestream.Dispose();
    filestream.Close();
    File.Delete(filePathOfRequestCopy);
}
```

```c#
public static Dictionary<string, MultiPartEntry> ParseBig(Stream localNetStream, string tempFolderPath)
{
    var mps = new Dictionary<string, MultiPartEntry>();
    var parser = new HttpMultipartParser.StreamingMultipartFormDataParser(localNetStream);
    Dictionary<string, FileStream> filestreamsByName = new Dictionary<string, FileStream>();
    parser.ParameterHandler += parameter =>
    {
        var mp = new MultiPartEntry();
        mp.Name = parameter.Name;
        mp.Value = parameter.Data;
        mps.Add(parameter.Name, mp);
    };
    parser.FileHandler += (name, fileName, type, disposition, buffer, bytes, partNumber) =>
    {
        // Write the part of the file we've received to a file stream. (Or do something else)
        // Assume that filesreamsByName is a Dictionary<string, FileStream> of all the files
        // we are writing.
        if (!filestreamsByName.ContainsKey(fileName))
        {
            var filepath = tempFolderPath + "/" + fileName;
            try
            {
                var filestream = File.Create(filepath);
                filestreamsByName.Add(fileName, filestream);
            }
            catch (System.Exception e)
            {
                Debug.LogError("error creating new file in temp folder");
            }
            var mp = new MultiPartEntry();
            mp.Name = name;
            mp.Filename = fileName;
            mp.Value = filepath;
            //KeyValuePair<string, MultiPartEntry>
            mps.Add(name, mp);
        }
        try
        {
            filestreamsByName[fileName].Write(buffer, 0, bytes);
            // Modified StreamingMultipartFormDataParser at:
            // "We've found an end. We need to consume all the binary up to it"
            //  FileHandler(name, filename, contentType, contentDisposition, fullBuffer, endPos - bufferNewlineLength, -1);
            if (partNumber == -1) // the last chunk/part for this file
            {
                filestreamsByName[fileName].Dispose();
                filestreamsByName[fileName].Close();
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError("error using filestreamsByName write");
            throw e;
        }
    };

    // You can parse synchronously:
    parser.Run();
    return mps;
}

```
