### ISSUE TITLE
Maintain an IMultipartFormDataParser interface

### ISSUE THREAD

**Issue by ConnorJBishop** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#93]
First of all thank you for creating this great lib. I am using it to parse the raw body from an AWS API Gateway event. Perfect use case 👍 

Would you consider maintaining an interface for MultipartFormDataParser so that I can't more easily test my code which depends on your lib.

Thanks again,
Connor

**Comment by Jericho** [comment]
I am very glad you find the library useful and thank you for the kind words. Having said that, it's important to point out that @Vodurden deserves the credit for creating this library and maintaining it for several years. I was an enthusiastic user for a long time and became the maintainer about a year and a half ago.

**Comment by Jericho** [comment]
I really like your idea of an interface if it makes it easier to mock the parser and test your code. The interface could be as simple as something like this:

```csharp
public interface IMultipartFormDataParser
{
    IReadOnlyList<FilePart> Files { get; }
    IReadOnlyList<ParameterPart> Parameters { get; }
}
```

**Comment by ConnorJBishop** [comment]
Thanks for addressing this so quickly!
