### ISSUE TITLE
Breaking changes in release 5.0.0

### ISSUE THREAD

**Issue by Jericho** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#96]
[Version 5.0.0](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/releases/tag/5.0.0) introduces a few breaking changes and I want to offer some tips on how to upgrade from a previous version:

**1. Obsolete MultipartFormDataParser constructors have been removed**
The various MultipartFormDataParser constructors had been marked as obsolete for more than a year and they were finally removed in version 5.0.0. This means that you may have code to instantiate a parser that looks similar to this:
```csharp
var myParser = new MultipartFormDataParser(stream);
```

This code no longer works and must be replaced with one of the following:
```csharp
// Sync
var myParser = MultipartFormDataParser.Parse(stream);

// Async
var myParser = await MultipartFormDataParser.ParseAsync(stream).ConfigureAwait(false);
```

**2. Additional parameter passed to the FileHandler delegate when a file "chunk" is streamed**
This applies to more advanced scenarios where you use the "streaming" parser. In such a scenario, you specify how to handle files that may be posted with the form with code similar to the following:
```csharp
var parser = new StreamingMultipartFormDataParser(stream);
parser.FileHandler += (name, fileName, type, disposition, buffer, bytes, partNumber) =>
{
    // do something
}
```

In release 5.0.0, you will get the following error when you attempt to compile your code: `CS1593 Delegate 'StreamingMultipartFormDataParser.FileStreamDelegate' does not take 7 arguments`. This is because a new parameter has been added to the `FileHandler` . Therefore, you must specify the FileHandler delegate like this:
```csharp
parser.FileHandler += (name, fileName, type, disposition, buffer, bytes, partNumber, additionalProperties) =>
{
    // do something
}
```

The new parameter will contain an enumeration of 'additional' properties that are associated with the file. In general, this enumeration will be empty as it is quite rare to have additional properties associated with a file but it can be very useful in certain scenarios. For instance, if you are parsing data posted by the Alexa service, each file will have a `Content-ID` property.

Please note that this does not affect you if you use the "standard" parser (as opposed to the "streaming" parser) like so: 
```csharp
var myParser = MultipartFormDataParser.Parse(stream);`.
```

**3. Properties changed to read-only**
There are a few properties that were always intended to be read-only but were inadvertently configured to be read/write. This oversight has been corrected and you can no longer modify these properties. 

Specifically: all the properties on the `FilePart` and `ParameterPart` classes as well as the `Parameters` and the `Files` properties on the `MultipartFormDataParser` class were corrected to ensure their content cannot be modified.

**4. Binary breaking changes**
There are other changes included in release 5.0.0 that are technically considered "breaking changes" because replacing the assembly of HttpMultipartDataParser currently used by your application with this latest one would cause your app to stop working. However these changes require no code change on your part. All that's needed is for you to recompile your code when referencing the latest NuGet package.

These changes are:
- Several methods and constructors overloads were eliminated and replaced with overloads with optional parameters
- Interfaces were added to the MultipartFormDataParser and StreamingMultipartFormDataParser classes. This enables you to mock these classes when unit testing your code

**Conclusion**
Hopefully these tips will help you transition to the latest release but post a comment if something is not clear and I'll update my tips.

As always, your feedback is greatly appreciated. Let me know if this is helpful.

**Comment by potchy** [comment]
I used your library for a project and it worked wonderfully better than .NET's built-in parser when dealing with large files.
Thanks a lot! 🎉

**Comment by Jericho** [comment]
Thank you for the great feedback. Really appreciate it!
