### ISSUE TITLE
StreamingMultipartFormDataParser - process large file >2gb

### ISSUE THREAD

**Issue by KreutzerCode** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#97]
Question

I am trying to process a large file from a stream using StreamingMultipartFormDataParser. More precisely, the stream of a TcpClient. I have encountered the problem that the input stream is processed but does not exit the FileHandler loop afterwards. To process the large file I proceeded as follows:

Methode to process stream:
![grafik](https://user-images.githubusercontent.com/53813841/110236335-7356e180-7f35-11eb-8506-63aae7bc372f.png)

And the Methode call: 
![grafik](https://user-images.githubusercontent.com/53813841/110236365-a4cfad00-7f35-11eb-8a90-e54edfa3f8b9.png)

As also noted in the comment, according to my understanding, the loop should still be exited so that I can close the filestream.
When I interrupt the programme, the filestream is closed and the file appears.

Am I making a mistake here when using StreamingMultipartFormDataParser? I have investigated a lot but could not find any clues. I have no problems using MultipartFormDataParser.Parse and would be very happy to be able to use this project for processing large files as well.

Many thanks in advance!

**Comment by Jericho** [comment]
This sounds very similar to the issue discussed in #92. Please review it and let me know if any of the suggestions in that other issue are helpful.

**Comment by KreutzerCode** [comment]
Thanks for the quick response! 
Yes that looks promising.  I'll take a closer look as soon as possible and then let you know again.

**Comment by KreutzerCode** [comment]
I guess I can work with that. Thanks again for the reference, the issue can hereby be closed.
